<a href="https://colab.research.google.com/github/Abubakar26/CNN-Fyp/blob/master/cnnp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive 
drive.mount('/content/drive')
DATA_PATH = "/content/drive/My Drive/Colab Notebooks"
import pickle as pk
from sklearn.utils import shuffle
import numpy as np
import matplotlib.pyplot as plt
import keras 
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D
from keras.layers import Dense,Dropout,Flatten
from sklearn.model_selection import train_test_split as tts
import pandas as pd
batch_size = 128
num_classes = 2
epochs = 12
import os
path="/home/ab/Downloads/ChinaSet_AllFiles/"
#more,directory,files=next(os.walk(path))
#print(directory)
img_rows, img_cols = 90, 90
pickle_in1=open(DATA_PATH+"/Nig","rb")
X=pk.load(pickle_in1)
pickle_in2=open(DATA_PATH+"/Nig2","rb")
Y=pk.load(pickle_in2)
print(X)
print(Y)
X,Y=shuffle(X,Y)
x_train,x_test,y_train,y_test = tts(X,Y,train_size=0.8)
# convert class vectors to binary class matrices
x_train=np.array(x_train)
y_train=np.array(y_train)
x_test=np.array(x_test)
y_test=np.array(y_test)

print("Xtrain",x_train.shape)
print("Ytrain",y_train.shape)
print("Ytest",y_test.shape)
print("Xtest",x_test.shape)

#Y_train = keras.utils.to_categorical(y_train)
X_test = keras.utils.to_categorical(x_test)
X_train=keras.utils.to_categorical(x_train)
#print(Y_train)
#print(y_train)
#print(x_test)
#print(y_test)
#rint(Y_test.shape)
print(X_train.shape)
#print(Y_test[0])

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='sigmoid',
                 input_shape=(90,90,256)))
model.add(Conv2D(64, (3, 3), activation='sigmoid',input_shape=(90,90,256)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='relu'))
model.compile(loss=keras.losses.sparse_categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])
model.fit(X_train,y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_split=0.1,shuffle=True)
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score)
print('Test accuracy:', score)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[[[[ 16]
   [ 13]
   [ 11]
   ...
   [  8]
   [  2]
   [  3]]

  [[ 10]
   [  9]
   [  7]
   ...
   [  5]
   [  8]
   [  8]]

  [[ 10]
   [  7]
   [  5]
   ...
   [  3]
   [  3]
   [  7]]

  ...

  [[ 40]
   [ 37]
   [ 95]
   ...
   [ 41]
   [ 10]
   [  0]]

  [[ 36]
   [ 34]
   [ 47]
   ...
   [  2]
   [ 10]
   [  0]]

  [[ 91]
   [ 56]
   [ 24]
   ...
   [  6]
   [  9]
   [  0]]]


 [[[ 54]
   [ 46]
   [ 47]
   ...
   [ 73]
   [ 78]
   [ 91]]

  [[ 50]
   [ 40]
   [ 37]
   ...
   [ 66]
   [ 71]
   [ 83]]

  [[ 42]
   [ 35]
   [ 30]
   ...
   [ 66]
   [ 69]
   [ 79]]

  ...

  [[124]
   [131]
   [136]
   ...
   [ 55]
   [ 56]
   [ 71]]

  [[164]
   [164]
   [170]
   ...
   [ 55]
   [ 57]
   [ 69]]

  [[  0]
   [  0]
   [  0]
   ...
   [131]
   [131]
   [136]]]


 [[[ 16]
   [ 16]
   [ 16]
   ...
   [ 20]
   [ 21]
   [ 20]]

  [[ 15]
   [ 16]
   [ 15]
   ...
